### ISSUE TITLE
Apply continuous delivery using Hookshot

### ISSUE THREAD

**Issue by leobalter** [bocoup/new-people#12]

**Comment by leobalter** [comment]
@tkellen can you provide me a documentation on how to set up our hookshot hooks?

**Comment by leobalter** [comment]
this is a blocker to solve this issue

**Comment by tkellen** [comment]
Documentation will be posted here:
https://github.com/bocoup/infrastructure/wiki/Continuous-Delivery

It is unlikely I will be able to get to this until tomorrow AM.

**Comment by tkellen** [comment]
Docs updated thanks to @brianloveswords. Let me know if you run into any blockers.

**Comment by leobalter** [comment]
:clap: :clap: Thanks!

**Comment by brianloveswords** [comment]
When you make the changes to `infrastruture`, tag me in the PR so I can
review!

On Tue, Nov 17, 2015 at 4:16 PM, Leo Balter <notifications@github.com>
wrote:

> [image: :clap:] [image: :clap:] Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bocoup/new-people/issues/12#issuecomment-157509701>.
>



-- 
Brian

**Comment by leobalter** [comment]
WOT!

I'll test it creating the production branch.

**Comment by tkellen** [comment]
Hey @leobalter, have a closer look at the docs, you're missing a configuration file!

**Comment by leobalter** [comment]
oops

**Comment by leobalter** [comment]
@brianloveswords @tkellen, I need help!

Hookshot is failing due to a missing password, as you can see at: http://hookshot.bocoup.com:1469/tasks/23306807-776e-4e6c-b300-1a811d01fbbf

You reproduce this error manually with:

```
$ ansible-playbook deploy/ansible/deploy.yml --inventory=deploy/ansible/inventory/staging
```

I'll follow this comment with a check list from each step from the docs

**Comment by leobalter** [comment]
should I include secrets? https://github.com/bocoup/OpenVisConf.com/blob/master/deploy/ansible/roles/deploy/tasks/secrets.yml

**Comment by tkellen** [comment]
Nope! I will take a peek at this first thing tomorrow.

**Comment by leobalter** [comment]
It's WORKING! OMG WOT

**Comment by tkellen** [comment]
Ahahaha what was it?

**Comment by brianloveswords** [comment]
Pinged you in slack about it, but the new-people-staging.bocoup.com server wasn't set up for passwordless sudo for the `robocoup` user. I ssh'd and `visudo`'d manually to fix it, but we should figure out why (or if I'm misunderstood in thinking that should happen automatically on initial server provision)

**Comment by tkellen** [comment]
The deploy playbook ideally shouldn't need root access--that's probably the
culprit. We should check the deployment workflow to confirm we aren't doing
that by default

**Comment by tkellen** [comment]
Strange. The `wheel` group should have access to passwordless sudo by defaut:

https://github.com/bocoup/infrastructure/blob/master/maintenance/grant-user-access.yml#L15-L21
https://github.com/bocoup/infrastructure/blob/master/inventory/users.yml#L4
